apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-controller
spec:
  replicas: 1
  selector:
    app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: developercyg111/flaskapi
        name: springboot
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-node-deployment
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask
