apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-controller
spec:
  replicas: 1
  selector:
    app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: developercyg111/flaskapi
        name: springboot
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: flask
